### ISSUE TITLE
model.transform(text)

### ISSUE THREAD

**Issue by techat** [openai/generating-reviews-discovering-sentiment#11]
Is text a list of words?
It seems the max length of element in the text list is 60. 

from encoder import Model
model = Model()
text = ['demo!']
text_features = model.transform(text)

**Comment by yg37** [comment]
I don't think so. THe ``preprocess`` function is utils.py maps text into bytes.

**Comment by yg37** [comment]
I think the ```preprocess``` function in utils.py transform them into bytes

**Comment by Newmu** [comment]
It's a list of "documents" - arbitrary length pieces of text you would like to compute a feature representation of.
