### ISSUE TITLE
Is the sentiment neuron at position 3159?

### ISSUE THREAD

**Issue by aykutfirat** [openai/generating-reviews-discovering-sentiment#2]

**Comment by Newmu** [comment]
2388 is the unit visualized and the single experiment results are reported on in the paper

**Comment by bitliner** [comment]
Extracting the 2388-th does not work for me. I always get 0 as value.

I used examples that are predicted as positive in the paper. 

Example:

```
if __name__ == '__main__':
    mdl = Model()
    text = [
        'too bad!', 
        'it was so cool, beautiful', 
        'the screenplay and the directing were horrendous', 
        'best books'
    ]
    text_features = mdl.transform(text)
    print('shape')
    print(text_features.shape)
    sentiment = text_features[:, 2388]
    print('sentiment')
    print(sentiment)
```

**Comment by dthiagarajan** [comment]
Referenced in #3 - it's something to do with how HTMLParser.HTMLParser().unescape(text) works. I ran into the same problem trying it with Python 2, but wasn't able to resolve it.
