### ISSUE TITLE
Error with html.unescape()

### ISSUE THREAD

**Issue by hardikmeisheri** [openai/generating-reviews-discovering-sentiment#24]
From what i have read, this is solved for python 3.5. It would be great if someone can suggest solution for this error in python 2.7. Also please post requirements in a text file to help understand which versions are needed.

**Comment by fedorzh** [comment]
text = HTMLParser.HTMLParser().unescape(text)

**Comment by fedorzh** [comment]
Apparently this doesn't work #3
