### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by guillitte** [openai/generating-reviews-discovering-sentiment#26]
For those interested, I converted the model to Pytorch 
![capture du 2017-05-06 15-23-36](https://cloud.githubusercontent.com/assets/13494525/25772641/12021b04-3270-11e7-9023-b90ec4742d90.png)

[https://github.com/guillitte/pytorch-sentiment-neuron](url)

**Comment by Newmu** [comment]
Cool! I've added a link to the readme. https://github.com/openai/generating-reviews-discovering-sentiment/commit/d1c4c18ac4888ad767881cf6ab522d91609983f0
