### ISSUE TITLE
Reproducing the Stanford Sentiment Treebank result from paper?

### ISSUE THREAD

**Issue by AjayTalati** [openai/generating-reviews-discovering-sentiment#27]
Hi, 

I just wondered if anyone has trained a binary classifier to reproduce the result for `SST` on page 4 of the paper?

If so is there any code for this?

Thanks a lot,

Aj

**Comment by loretoparisi** [comment]
@embreinhardt This would be helpful to compare against a de facto dataset used for sentiment analysis with [RNN networks](https://nlp.stanford.edu/sentiment/code.html) - demo [here](http://nlp.stanford.edu:8080/sentiment/rntnDemo.html)

**Comment by Newmu** [comment]
We've added a demo of training a sentiment classifier using the model's features which reproduces the binary SST result https://github.com/openai/generating-reviews-discovering-sentiment/commit/83d940d132fbd585deb63b8e3fcb523ea9557683
