### ISSUE TITLE
Is neutral prediction possible?

### ISSUE THREAD

**Issue by itisjoshi** [openai/generating-reviews-discovering-sentiment#34]
We are trying to build sentiment analysis for email conversations. The problem we are facing is most of the emails were neutral conversations.

This models predicts neutral sentiment as positive or negative.

My questions is there any specific range for negative, positive and neutral sentiments?

Is it possible to predict sentiments as neutral?

**Comment by ahirner** [comment]
The typical ranges for sentiments inferred or generated are discussed in #21.

**Comment by Newmu** [comment]
One of the tasks the paper benchmarks on is the very negative, negative, neutral, positive, very positive version of the Stanford Sentiment Treebank and it performs close to state of the art even though it includes neutral suggesting there's no fundamental issue with neutral.

The more likely problem is out-of-domain issues. The model is trained on product reviews which can have pretty different language from an email. There's no inherent "range" but you could probably fit simple thresholds for your task given only a few labeled negative, neutral, and positive examples.
