### ISSUE TITLE
Compatibility with TF >= 1.0.0

### ISSUE THREAD

**Issue by g3n1uss** [openai/generating-reviews-discovering-sentiment#4]
`tf.unpack` (used in 90th line of encoder.py) [was deprecated](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#major-features-and-improvements-1) in favor of `tf.unstack` since release 1.0.0. However, a simple replacement `tf.unpack`->`tf.unstack` does not work because `tf.split` has been changed too.

A full compatible with TF 1.0.1 version can be found [here](https://github.com/g3n1uss/generating-reviews-discovering-sentiment/tree/compatibleWithTF101). Thanks to @blester125

**Comment by rdeese** [comment]
The problem persists even after running [the TensorFlow upgrade utility](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility) on `encoder.py`. With python 3.5.0 and tensorflow 1.0.1 I get:

```bash
*> python encoder.py 
Traceback (most recent call last):
  File "encoder.py", line 209, in <module>
    mdl = Model()
  File "encoder.py", line 143, in __init__
    cells, states, logits = model(X, S, M, reuse=False)
  File "encoder.py", line 93, in model
    inputs = [tf.squeeze(v, [1]) for v in tf.split(axis=1, num_or_size_splits=nsteps, value=words)]
  File "/Users/rupertdeese/.pyenv/versions/3.5.0/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1203, in split
    num = size_splits_shape.dims[0]
IndexError: list index out of range
```

**Comment by g3n1uss** [comment]
@rdeese Yes, that is because `tf.split` has been changed too.

**Comment by rdeese** [comment]
@g3n1uss well, the upgrade utility is supposed to handle the changes in `tf.split`-- it makes changes to those function calls. The changes don't resolve the error though.

**Comment by g3n1uss** [comment]
@rdeese a good point! Thanks!

**Comment by blester125** [comment]
nsteps is passed into tf.split as the num_os_size_splits argument but nsteps is a "Dimension" rather than an integer. When this gets to tf.split, if isinstance(num_or_size_splits, six.integer_types): returns false and this code is run
    size_splits = ops.convert_to_tensor(num_or_size_splits)
    if num is None:
      size_splits_shape = size_splits.get_shape()
      num = size_splits_shape.dims[0]
but the Dimension's shape is an empty list so .dims[0] fails. 

nsteps should be converted to an integer before being passed into the function

**Comment by g3n1uss** [comment]
@blester125 You are right. I created fully compatible with 1.0.1 version  [here](https://github.com/g3n1uss/generating-reviews-discovering-sentiment/tree/compatibleWithTF101).

**Comment by bkj** [comment]
@g3n1uss Is the example supposed to yield a vector of all `0`s in your fork?

**Comment by g3n1uss** [comment]
@bkj a vector. On my `tensorflow-gpu (1.0.1)` the example prints 
```
0.496 seconds to transform 1 examples
(1, 4096)
```

**Comment by cerisara** [comment]
@g3n1uss Great ! Just cloned your TF1.0.1 version and it works ! For the others: don't forget
git checkout remotes/origin/compatibleWithTF101

Thanks

**Comment by Newmu** [comment]
Migrated as of https://github.com/openai/generating-reviews-discovering-sentiment/commit/83d940d132fbd585deb63b8e3fcb523ea9557683
